export const SYNC_COMMAND = {
  PING: 'PING',
  PULL_ORGS_FROM_ECOMV2: 'PULL_ORGS_FROM_ECOMV2',
  PULL_ORDERS_FROM_ECOM_BY_COMPANY_ID: 'PULL_ORDERS_FROM_ECOM_BY_COMPANY_ID',
  PULL_STORES_FROM_ECOM_BY_COMPANY_ID_V2:
    'PULL_STORES_FROM_ECOM_BY_COMPANY_ID_V2',
  PULL_STORES_FROM_ECOM_V2: 'PULL_STORES_FROM_ECOM_V2',
  PULL_DISTRIBUTORS_FROM_ECOM_BY_COMPANY_ID_V2:
    'PULL_DISTRIBUTORS_FROM_ECOM_BY_COMPANY_ID_V2',
  PULL_DISTRIBUTORS_FROM_ECOM: 'PULL_DISTRIBUTORS_FROM_ECOM',
  PULL_LOCATIONS_FROM_ECOM: 'PULL_LOCATIONS_FROM_ECOM',
  UPDATE_COMPANY_REF: 'UPDATE_COMPANY_REF',
  PULL_PRODUCTS_FROM_ECOM_BY_COMPANY: 'PULL_PRODUCTS_FROM_ECOM_BY_COMPANY',
  PULL_INVENTORIES: 'PULL_INVENTORIES',
  ECOM_PUSH_INVENTORIES_BY_ORG_ID: 'ECOM_PUSH_INVENTORIES_BY_ORG_ID',
  PULL_DISTRIBUTION_ARES: 'PULL_DISTRIBUTION_ARES',
  ECOM_PUSH_ORG: 'ECOM_PUSH_ORG',
  ECOM_PUSH_ORG_PARENT: 'ECOM_PUSH_ORG_PARENT',
  ECOMV2_PUSH_PRODUCT: 'ECOMV2_PUSH_PRODUCT',
  ECOMV2_PUSH_PRODUCT_VARIANT: 'ECOMV2_PUSH_PRODUCT_VARIANT',
  ECOMV2_PUSH_ORDER: 'ECOMV2_PUSH_ORDER',
  ECOMV2_PUSH_ORDER_V2: 'ECOMV2_PUSH_ORDER_V2',
  ECOMV2_PUSH_RETURN_ORDER: 'ECOMV2_PUSH_RETURN_ORDER',
  ECOMV2_PUSH_INVENTORY: 'ECOMV2_PUSH_INVENTORY',
  ECOMV2_PUSH_INVENTORY_V2: 'ECOMV2_PUSH_INVENTORY_V2',
  ECOMV2_PUSH_BUSINESS_TYPE: 'ECOMV2_PUSH_BUSINESS_TYPE',
  ECOMV2_PUSH_COMPANY: 'ECOMV2_PUSH_COMPANY',
  ECOMV2_PUSH_DISTRIBUTOR: 'ECOMV2_PUSH_DISTRIBUTOR',
  ECOMV2_PUSH_STORE: 'ECOMV2_PUSH_STORE',
  UPDATE_SYNC_STORE_MISSING_DISTRIBUTOR:
    'UPDATE_SYNC_STORE_MISSING_DISTRIBUTOR',
  ECOMV2_PULL_STORE: 'ECOMV2_PULL_STORE',
  SYNC_LOG: 'SYNC_LOG',
  PULL_CATEGORIES: 'PULL_CATEGORIES',
  PULL_MASTERDATAS: 'PULL_MASTERDATAS',
  PULL_COMPANY: 'PULL_COMPANY',
  SYNC_UPDATE_STORE: 'SYNC_UPDATE_STORE',
  SYNC_HISTORY_STORAGE: 'SYNC_HISTORY_STORAGE',
  SYNC_HISTORY_STORAGE_UPDATE_ITEM: 'SYNC_HISTORY_STORAGE_UPDATE_ITEM',
  ECOPAY_GET_INTERNAL_STORES: 'ECOPAY_GET_INTERNAL_STORES',
  ECOPAY_GET_STORES: 'ECOPAY_GET_STORES',
  ECOPAY_GET_INTERNAL_QRCODE_MAPPING_SCAN:
    'ECOPAY_GET_INTERNAL_QRCODE_MAPPING_SCAN',
  ECOPAY_UPDATE_INTERNAL_QRCODE_MAPPING:
    'ECOPAY_UPDATE_INTERNAL_QRCODE_MAPPING',
  ECOPAY_UPDATE_INTERNAL_QRCODE_UPDATE: 'ECOPAY_UPDATE_INTERNAL_QRCODE_UPDATE',
  ECOPAY_GET_INTERNAL_BANK: 'ECOPAY_GET_INTERNAL_BANK',
  UPDATE_STORE_QRCODE_MAPPING_CODE: 'UPDATE_STORE_QRCODE_MAPPING_CODE',
  SYNC_SCOPE_FROM_KEYCLOARK: 'SYNC_SCOPE_FROM_KEYCLOARK',
  SYNC_RESOURCE_FROM_KEYCLOARK: 'SYNC_RESOURCE_FROM_KEYCLOARK',
  SYNC_POLICY_FROM_KEYCLOARK: 'SYNC_POLICY_FROM_KEYCLOARK',
  SYNC_PERMISSION_FROM_KEYCLOARK: 'SYNC_PERMISSION_FROM_KEYCLOARK',
  PUSH_SALEMAN_ACTION_HISTORY: 'PUSH_SALEMAN_ACTION_HISTORY',
  // PUSH_SALEMAN_SAVE_HISTORY: 'PUSH_SALEMAN_SAVE_HISTORY',
  // PUSH_SALEMAN_SAVE_HISTORY_V2: 'PUSH_SALEMAN_SAVE_HISTORY_V2',
  PUSH_SALEMAN_SAVE_MAP_LOCATION: 'PUSH_SALEMAN_SAVE_MAP_LOCATION',
  PUSH_SALEMAN_SAVE_ECOPAY_STORE: 'PUSH_SALEMAN_SAVE_ECOPAY_STORE',
  PUSH_UPDATED_STORE_TO_ECOM: 'PUSH_UPDATED_STORE_TO_ECOM',
  FIND_AND_PUSH_UPDATED_STORE_TO_ECOM: 'FIND_AND_PUSH_UPDATED_STORE_TO_ECOM',
  FIND_AND_PUSH_UPDATED_DISTRIBUTOR_TO_ECOM:
    'FIND_AND_PUSH_UPDATED_DISTRIBUTOR_TO_ECOM',
  PUSH_UPDATED_DISTRIBUTOR_TO_ECOM: 'PUSH_UPDATED_DISTRIBUTOR_TO_ECOM',
  PUSH_CREATED_STORE_TO_ECOM: 'PUSH_CREATED_STORE_TO_ECOM',
  SYNC_ORG_PROFILE_TO_ECOM: 'SYNC_ORG_PROFILE_TO_ECOM',
  CALCULATE_KPI_ORDER: 'CALCULATE_KPI_ORDER',
  CALCULATE_KPI_STORE: 'CALCULATE_KPI_STORE',
  CALCULATE_KPI_WORKING_TIME: 'CALCULATE_KPI_WORKING_TIME',
  CALCULATE_KPI_VISIT_STORE: 'CALCULATE_KPI_VISIT_STORE',
  // ACCUMULATE_PROCESS: 'ACCUMULATE_PROCESS',
  UPDATE_RELATED_ROUTE_INFO: 'UPDATE_RELATED_ROUTE_INFO',
  // SAVE_INFO: 'SAVE_INFO',
  SEND_TELEGRAM_SYSTEM: 'SEND_TELEGRAM_SYSTEM',
  SEND_TELEGRAM_ACTION_HISTORY: 'SEND_TELEGRAM_ACTION_HISTORY',
  SEND_TELEGRAM_ACTION_HEALTH_SYSTEM: 'SEND_TELEGRAM_ACTION_HEALTH_SYSTEM',
  SEND_TELEGRAM_CUSTOMER_SERVICE: 'SEND_TELEGRAM_CUSTOMER_SERVICE',
  SEND_FIREBASE: 'SEND_FIREBASE',
  SEND_FIREBASE_TOPIC: 'SEND_FIREBASE_TOPIC',
  SEND_NOTIFY_TO_MERCHANT: 'SEND_NOTIFY_TO_MERCHANT',
  SET_STORE_CHECK_IN_SCHEDULER: 'SET_STORE_CHECK_IN_SCHEDULER',
  DEL_STORE_CHECK_IN_SCHEDULER: 'DEL_STORE_CHECK_IN_SCHEDULER',

  // CTTB
  // IMPORT_EVENT_PARTICIPANT: 'IMPORT_EVENT_PARTICIPANT',
  // IMPORT_EVENT_REWARDING: 'IMPORT_EVENT_REWARDING',
  SET_EVENT_EXPIRED_SCHEDULER: 'SET_EVENT_EXPIRED_SCHEDULER',
  SET_EVENT_REWARD_EXPIRED: 'SET_EVENT_REWARD_EXPIRED',
  SET_EVENT_PARTICIPANT_EXPIRED_SCHEDULER:
    'SET_EVENT_PARTICIPANT_EXPIRED_SCHEDULER',
  SET_EVENT_PROCESS_FINISH_SCHEDULER: 'SET_EVENT_PROCESS_FINISH_SCHEDULER',
  // EXCUTE_EVENT_PROCESS_FINISH_SCHEDULER:
  //     'EXCUTE_EVENT_PROCESS_FINISH_SCHEDULER',
  DEL_EVENT_EXPIRED_SCHEDULER: 'DEL_EVENT_EXPIRED_SCHEDULER',
  AUTOMATICALLY_APPROVE_EVENT_PARTICIPANT:
    'AUTOMATICALLY_APPROVE_EVENT_PARTICIPANT',
  INACTIVE_EVENT: 'INACTIVE_EVENT', // CTTB ngưng hoạt động
  CALCULATE_ORDER_PROGRESS_OF_EVENT_PARTICIPANT_PROCESS:
    'CALCULATE_ORDER_PROGRESS_OF_EVENT_PARTICIPANT_PROCESS',
  GENERATE_PROCESSES_OF_EVENT_PARTICIPANT:
    'GENERATE_PROCESSES_OF_EVENT_PARTICIPANT',
  DEL_EVENT_PARTICIPANT_EXPIRED_SCHEDULER:
    'DEL_EVENT_PARTICIPANT_EXPIRED_SCHEDULER',

  // CTTL
  SET_EVENT_ACCUMULATE_EXPIRED_SCHEDULER:
    'SET_EVENT_ACCUMULATE_EXPIRED_SCHEDULER',
  DEL_EVENT_ACCUMULATE_SCHEDULER: 'DEL_EVENT_ACCUMULATE_SCHEDULER',
  SET_EVENT_ACCUMULATE_PROCESS_SCHEDULER:
    'SET_EVENT_ACCUMULATE_PROCESS_SCHEDULER',
  DEL_EVENT_ACCUMULATE_PROCESS_SCHEDULER:
    'DEL_EVENT_ACCUMULATE_PROCESS_SCHEDULER',
  SET_EVENT_ACCUMULATE_PARTICIPANT_EXPIRED_SCHEDULER:
    'SET_EVENT_ACCUMULATE_PARTICIPANT_EXPIRED_SCHEDULER',
  DEL_EVENT_ACCUMULATE_PARTICIPANT_SCHEDULER:
    'DEL_EVENT_ACCUMULATE_PARTICIPANT_SCHEDULER',
  SET_EVENT_ACCUMULATE_REWARD_EXPIRED_SCHEDULER:
    'SET_EVENT_ACCUMULATE_REWARD_EXPIRED_SCHEDULER',
  DEL_EVENT_ACCUMULATE_REWARD_SCHEDULER:
    'DEL_EVENT_ACCUMULATE_REWARD_SCHEDULER',
  GET_STORES_PARTICIPATING_EVENT_ACCUMULATE_THIRD_PARTY:
    'GET_STORES_PARTICIPATING_EVENT_ACCUMULATE_THIRD_PARTY',

  // CREATE_PLAN_REAL_ROUTE_BY_ROUTE: 'CREATE_PLAN_REAL_ROUTE_BY_ROUTE',
  SAVE_REPORT_SUMMARY: 'SAVE_REPORT_SUMMARY',
  // UPDATE_RELATED_FURTURE_ROUTE_INFO: 'UPDATE_RELATED_FURTURE_ROUTE_INFO',
  CREATE_REAL_ROUTE_MANUALLY: 'CREATE_REAL_ROUTE_MANUALLY',
  UPDATE_RELATED_THIRD_PARTY_REFERENCE: 'UPDATE_RELATED_THIRD_PARTY_REFERENCE',
  SUMMARY_REPORT_KPI_ORDER: 'SUMMARY_REPORT_KPI_ORDER',
  SUMMARY_REPORT_ORDER_APPLY_TIME: 'SUMMARY_REPORT_ORDER_APPLY_TIME',
  SUMMARY_REPORT_CHECKIN_VISIT_STORE: 'SUMMARY_REPORT_CHECKIN_VISIT_STORE',
  SUMMARY_REPORT_KPI_CHECKOUT_VISIT_STORE:
    'SUMMARY_REPORT_KPI_CHECKOUT_VISIT_STORE',
  SUMMARY_REPORT_VISIT_STORE: 'SUMMARY_REPORT_VISIT_STORE',
  SUMMARY_REPORT_CHECKOUT_VISIT_STORE_APPLY_TIME:
    'SUMMARY_REPORT_CHECKOUT_VISIT_STORE_APPLY_TIME',
  SUMMARY_REPORT_KPI_NEW_STORE: 'SUMMARY_REPORT_KPI_NEW_STORE',
  SUMMARY_REPORT_STORE: 'SUMMARY_REPORT_STORE',
  SUMMARY_REPORT_KPI_CHECKOUT_WORKING_TIME:
    'SUMMARY_REPORT_KPI_CHECKOUT_WORKING_TIME',
  SUMMARY_REPORT_KPI_CHECKOUT_WORKING_TIME_APPLY_TIME:
    'SUMMARY_REPORT_KPI_CHECKOUT_WORKING_TIME_APPLY_TIME',
  SUMMARY_REPORT_CHECKOUT_WORKING_TIME_APPLY_TIME:
    'SUMMARY_REPORT_CHECKOUT_WORKING_TIME_APPLY_TIME',
  SUMMARY_REPORT_KPI_CHECKIN_WORKING_TIME:
    'SUMMARY_REPORT_KPI_CHECKIN_WORKING_TIME',
  SUMMARY_REPORT_CHECKIN_WORKING_TIME_APPLY_TIME:
    'SUMMARY_REPORT_CHECKIN_WORKING_TIME_APPLY_TIME',
  SUMMARY_REPORT_ERROR_LOG: 'SUMMARY_REPORT_ERROR_LOG',
  SUMMARY_REPORT_ORDER_STORE: 'SUMMARY_REPORT_ORDER_STORE',
  HANDLE_CRON_REAL_ROUTE: 'HANDLE_CRON_REAL_ROUTE',
  HANDLE_THIRD_PARTY_TRANSPORT: 'HANDLE_THIRD_PARTY_TRANSPORT',
  GET_INVENTORY_FROM_ECOMV2: 'GET_INVENTORY_FROM_ECOMV2',
  ECOMV2_VALIDATE_ORDER: 'ECOMV2_VALIDATE_ORDER',
  ECOMV2_CREATE_ORDER: 'ECOMV2_CREATE_ORDER',
  KPI_REPORT_VISIT_STORE: 'KPI_REPORT_VISIT_STORE',
  KPI_REPORT_WORKING_TIME_MULTI_THREAD: 'KPI_REPORT_WORKING_TIME_MULTI_THREAD',
  KPI_REPORT_WORKING_TIMES_MULTI_THREAD:
    'KPI_REPORT_WORKING_TIMES_MULTI_THREAD',
  KPI_REPORT_MULTI_THREADS: 'KPI_REPORT_MULTI_THREADS',
  UPDATE_KPI_TARGET: 'UPDATE_KPI_TARGET',
  KPI_REPORT_MONTH: 'KPI_REPORT_MONTH',
  COMPRESS_REPORT_SCHEDULER: 'COMPRESS_REPORT_SCHEDULER',
  EXPORT_FILE_SCHEDULER: 'EXPORT_FILE_SCHEDULER',

  // ASSET
  // ASSET_ASSIGN_FROM_THIRD_PARTY: 'ASSET_ASSIGN_FROM_THIRD_PARTY',
  // ASSET_RECALL_FROM_THIRD_PARTY: 'ASSET_RECALL_FROM_THIRD_PARTY',
  // GET_ASSET_VERIFY_HISTORY_FROM_THIRD_PARTY:
  //     'GET_ASSET_VERIFY_HISTORY_FROM_THIRD_PARTY',
  // GET_STORE_FROM_THIRD_PARTY: 'GET_STORE_FROM_THIRD_PARTY',
  // GET_MASTER_DATA_FROM_THIRD_PARTY: 'GET_MASTER_DATA_FROM_THIRD_PARTY',
  // PROCESS_IMPORT_ACCESS_DATA: 'PROCESS_IMPORT_ACCESS_DATA',
  // PROCESS_IMPORT_EMIT_MESSAGE_CHANGE_STATUS:
  //     'PROCESS_IMPORT_EMIT_MESSAGE_CHANGE_STATUS',
  // PROCESS_IMPORT_CHANGE_STATUS: 'PROCESS_IMPORT_CHANGE_STATUS',
  // PROCESS_IMPORT_HANDLE_DETAIL_DATA: 'PROCESS_IMPORT_HANDLE_DETAIL_DATA',
  // REPORT_MCP_FROM_THIRD_PARTY: 'REPORT_MCP_FROM_THIRD_PARTY',
  // REPORT_VISIT_HISTORY_FROM_THIRD_PARTY:
  //     'REPORT_VISIT_HISTORY_FROM_THIRD_PARTY',
  // REPORT_REVENUE_ORDER_FROM_THIRD_PARTY:
  //     'REPORT_REVENUE_ORDER_FROM_THIRD_PARTY',
  HANDLE_CRON_EXPIRED_ASSIGN_ROUTE: 'HANDLE_CRON_EXPIRED_ASSIGN_ROUTE',
  HANDLE_CRON_EXPIRED_SURVEY: 'HANDLE_CRON_EXPIRED_SURVEY',
  HANDLE_CRON_EXPIRED_KPI_TARGET: 'HANDLE_CRON_EXPIRED_KPI_TARGET',
  // ACTIVE_REACTIVE_STORE: 'ACTIVE_REACTIVE_STORE',
  COMPARE_ORDER: 'COMPARE_ORDER',
  COMPARE_STORE: 'COMPARE_STORE',
  ECOM_PUSH_ORG_V2: 'ECOM_PUSH_ORG_V2',

  COMPRESS_REPORT_MCP_THIRD_PARTY: 'COMPRESS_REPORT_MCP_THIRD_PARTY',
  COMPRESS_REPORT_VISIT_HISTORY_THIRD_PARTY:
    'COMPRESS_REPORT_VISIT_HISTORY_THIRD_PARTY',
  DMS_TO_DATA_SYNC_STORE_DISTRIBUTOR: 'DMS_TO_DATA_SYNC_STORE_DISTRIBUTOR',
  COMPARE_DISTRIBUTOR: 'COMPARE_DISTRIBUTOR',

  //REPORT SYNC
  REPORT_SYNC_STORE: 'REPORT_SYNC_STORE',
  REPORT_SYNC_ORDER: 'REPORT_SYNC_ORDER',
  REPORT_SYNC_ROUTE: 'REPORT_SYNC_ROUTE',
  REPORT_SYNC_REAL_ROUTE: 'REPORT_SYNC_REAL_ROUTE',
  REPORT_SYNC_WORKING_TIMES_DATA: 'REPORT_SYNC_WORKING_TIMES_DATA',
  UPDATE_STATUS_EXPORT_FILE: 'UPDATE_STATUS_EXPORT_FILE',
  GET_DATA_EXPORT_BY_ID: 'GET_DATA_EXPORT_BY_ID',
  GET_DATA_EXPORT_FILE_BY_ID: 'GET_DATA_EXPORT_FILE_BY_ID',
  GET_DATA_EXPORT_FILE_BY_QUERY: 'GET_DATA_EXPORT_FILE_BY_QUERY',
  GET_DATA_EXPORT_BY_QUERY: 'GET_DATA_EXPORT_BY_QUERY',
  RETRY_EXPORT_FILE: 'RETRY_EXPORT_FILE',
  CHECK_STATUS_EXPORT_FILE: 'CHECK_STATUS_EXPORT_FILE',
  UPDATE_EXPORT_FILE_BY_ID: 'UPDATE_EXPORT_FILE_BY_ID',
  UPDATE_EXPORT_BY_ID: 'UPDATE_EXPORT_BY_ID',
  UPDATE_PROCESS_EXPORT_EXPIRED: 'UPDATE_PROCESS_EXPORT_EXPIRED',
  UPDATE_STATUS_COMPRESS_EXPORT: 'UPDATE_STATUS_COMPRESS_EXPORT',
  DELETE_COMPRESS_EXPORT: 'DELETE_COMPRESS_EXPORT',
  DELETE_EXPORT_FILE: 'DELETE_EXPORT_FILE',
  CREATE_COMPRESS_EXPORT: 'CREATE_COMPRESS_EXPORT',
  DELETE_EXPORT_FILE_TEMP: 'DELETE_EXPORT_FILE_TEMP',
  //#region ROUTE
  // HANDLE_PLAN_ROUTE_REPORT: 'HANDLE_PLAN_ROUTE_REPORT',
  // UPDATE_EXPIRED_ROUTE: 'DMS_STORAGE_ROUTE.UPDATE_EXPIRED_ROUTE',
  // UPDATE_FUTURE_ROUTE: 'DMS_STORAGE_ROUTE.UPDATE_FUTURE_ROUTE',
  // UPDATE_RELATED_ROUTE: 'DMS_STORAGE_ROUTE.UPDATE_RELATED_ROUTE',
  //#endregion
  //REPORT MOBILE
  // REPORT_MOBILE_BUSINESS: 'REPORT_MOBILE_BUSINESS',
  // GET_ACTION_HISTORY_BY_ID: 'GET_ACTION_HISTORY_BY_ID',
  FIND_PLAN_ROUTE_BASE_ON_SYNCHORONIZED_ORDER:
    'DMS_REPORT_READ_PORTAL.FIND_PLAN_ROUTE_BASE_ON_SYNCHORONIZED_ORDER',
} as const;
