import { Value } from './config';

export const DMS_REPORT_WRITE: Value<'DMS_REPORT_WRITE'> = {
    name: 'DMS_REPORT_WRITE',
    isAck: true,
    prefetchCount: 5,
    queueOptions: {
        // messageTtl: 1800000,
        durable: true,
    },
    commands: {
        RETRY_COMPRESS_REPORT: {
            cmd: 'DMS_REPORT_WRITE.RETRY_COMPRESS_REPORT',
        },
        BACKUP_MIGRATE_KPI_DATA: {
            cmd: 'DMS_REPORT_WRITE.BACKUP_MIGRATE_KPI_DATA',
        },
        // SUMMARY_REPORT_ORDER_DETAIL_INVALID_DATA: {
        //     cmd: 'DMS_REPORT_WRITE.SUMMARY_REPORT_ORDER_DETAIL_INVALID_DATA',
    },
    topics: {
        SUMMARY_REPORT: 'DMS_REPORT_WRITE.SUMMARY_REPORT',
        // GENERATE_PLAN_ROUTE: 'DMS_REPORT_WRITE.GENERATE_PLAN_ROUTE',
        CALCULATE_SUMAMARY_REPORT_ORDER:
            'DMS_REPORT_WRITE.CALCULATE_SUMAMARY_REPORT_ORDER',
        CREATE_SUMMARY_REPORT_ORDER_DETAIL:
            'DMS_REPORT_WRITE.CREATE_SUMMARY_REPORT_ORDER_DETAIL',
        // COMPARE_SUMMARY_REPORT_ORDER_DETAIL:
        //     'DMS_REPORT_WRITE.COMPARE_SUMMARY_REPORT_ORDER_DETAIL',
        SUMMARY_REPORT_ORDER_WITHOUT_USER:
            'DMS_REPORT_WRITE.SUMMARY_REPORT_ORDER_WITHOUT_USER',
        FIND_SUMMARY_REPORT_WITHOUT_USER_BY_UPDATED_AT:
            'DMS_REPORT_WRITE.FIND_SUMMARY_REPORT_WITHOUT_USER_BY_UPDATED_AT',
        CALCULATE_SUMMARY_REPORT_WITHOUT_USER:
            'DMS_REPORT_WRITE.CALCULATE_SUMMARY_REPORT_WITHOUT_USER',
        REMOVE_REAL_ROUTE: 'DMS_REPORT_WRITE.REMOVE_REAL_ROUTE',
        SUMMARY_REPORT_UPDATE_CHECKOUT_END_DAY:
            'DMS_REPORT_WRITE.SUMMARY_REPORT_UPDATE_CHECKOUT_END_DAY',
        SUMMARY_REPORT_UPDATE_EXIRED_ROUTE:
            'DMS_REPORT_WRITE.SUMMARY_REPORT_UPDATE_EXIRED_ROUTE',
        BACKUP_MIGRATE_KPI_DATA: 'DMS_REPORT_WRITE.BACKUP_MIGRATE_KPI_DATA',
    },
};
// satisfies Value<'DMS_REPORT_WRITE'>;

export const DMS_REPORT_WRITE_ORDER_DETAIL: Value<'DMS_REPORT_WRITE_ORDER_DETAIL'> =
    {
        name: 'DMS_REPORT_WRITE_ORDER_DETAIL',
        isAck: true,
        prefetchCount: 1,
        commands: {
            SUMMARY_REPORT_ORDER_DETAIL_INVALID_DATA: {
                cmd: 'DMS_REPORT_WRITE_ORDER_DETAIL.SUMMARY_REPORT_ORDER_DETAIL_INVALID_DATA',
            },
        },
        topics: {
            CREATE_SUMMARY_REPORT_ORDER_DETAIL:
                'DMS_REPORT_WRITE_ORDER_DETAIL.CREATE_SUMMARY_REPORT_ORDER_DETAIL',
            COMPARE_SUMMARY_REPORT_ORDER_DETAIL:
                'DMS_REPORT_WRITE_ORDER_DETAIL.COMPARE_SUMMARY_REPORT_ORDER_DETAIL',
        },
    };
// satisfies Value<'DMS_REPORT_WRITE_ORDER_DETAIL'>;

export const DMS_REPORT_WRITE_SUMMARY_REPORT: Value<'DMS_REPORT_WRITE_SUMMARY_REPORT'> =
    {
        name: 'DMS_REPORT_WRITE_SUMMARY_REPORT',
        isAck: true,
        prefetchCount: 2,
        commands: {
            SUMMARY_REPORT_GENERATE_DEFAULT_DATA: {
                cmd: 'DMS_REPORT_WRITE_SUMMARY_REPORT.SUMMARY_REPORT_GENERATE_DEFAULT_DATA',
            },
        },
    };
//satisfies Value<'DMS_REPORT_WRITE_SUMMARY_REPORT'>;

export const DMS_REPORT_WRITE_COMPRESS: Value<'DMS_REPORT_WRITE_COMPRESS'> = {
    name: 'DMS_REPORT_WRITE_COMPRESS',
    isAck: false,
    prefetchCount: 1,
    commands: {},
    topics: {
        CREATE_COMPRESS_EXPORT:
            'DMS_REPORT_WRITE_COMPRESS.CREATE_COMPRESS_EXPORT',
        COMPRESS_REPORT_SCHEDULER:
            'DMS_REPORT_WRITE_COMPRESS.COMPRESS_REPORT_SCHEDULER',
    },
};
