import { Value } from './config';

export const DMS_REPORT_WRITE_KPI: Value<'DMS_REPORT_WRITE_KPI'> = {
    name: 'DMS_REPORT_WRITE_KPI',
    isAck: true,
    prefetchCount: 2,
    commands: {
        ADD_ASSIGN_OBJECT: { cmd: 'DMS_REPORT_WRITE_KPI.ADD_ASSIGN_OBJECT' },
        UPSERT: { cmd: 'DMS_REPORT_WRITE_KPI.UPSERT' },
        REMOVE_ACTIVE_USERS: {
            cmd: 'DMS_REPORT_WRITE_KPI.REMOVE_ACTIVE_USERS',
        },
        UPDATE_INACTIVE: {
            cmd: 'DMS_REPORT_WRITE_KPI.UPDATE_INACTIVE',
        },
        BACKUP_DATA: { cmd: 'DMS_REPORT_WRITE_KPI.BACKUP_DATA' },
        GENERATE_DEFAULT_DATA: {
            cmd: 'DMS_REPORT_WRITE_KPI.GENERATE_DEFAULT_DATA',
        },
        BACKUP_FIND_MISSING_ASSIGNED_AT: {
            cmd: 'DMS_REPORT_WRITE_KPI.BACKUP_FIND_MISSING_ASSIGNED_AT',
        },
    },
    topics: {
        CREATE_KPI_TARGET: 'DMS_REPORT_WRITE_KPI.CREATE_KPI_TARGET',
        UPDATE_KPI_TARGET: 'DMS_REPORT_WRITE_KPI.UPDATE_KPI_TARGET',
        CREATE_REPORT: 'DMS_REPORT_WRITE_KPI.CREATE_REPORT',
        BACKUP_ASSIGN_OBJECT: 'DMS_REPORT_WRITE_KPI.BACKUP_ASSIGN_OBJECT',
        UPDATE_ACTIVE_REACTIVE_STORE:
            'DMS_REPORT_WRITE_KPI.UPDATE_ACTIVE_REACTIVE_STORE',
        KPI_REPORT_UPDATE_AFTER_VISIT_PLAN_ROUTE:
            'DMS_REPORT_WRITE_KPI.KPI_REPORT_UPDATE_AFTER_VISIT_PLAN_ROUTE',
        UPDATE_EXPIRED_REPORT: 'DMS_REPORT_WRITE_KPI.UPDATE_EXPIRED_REPORT',
        UPDATE_STATUS_KPI_SUMMARY_BY_TIME:
            'DMS_REPORT_WRITE_KPI.UPDATE_STATUS_KPI_SUMMARY_BY_TIME',
    },
};
//satisfies Value<'DMS_REPORT_WRITE_KPI'>;
