import { Value } from './config';

export const DMS_REPORT_WRITE_GENERATE_DATA: Value<'DMS_REPORT_WRITE_GENERATE_DATA'> =
    {
        name: 'DMS_REPORT_WRITE_GENERATE_DATA',
        isAck: true,
        prefetchCount: 2,
        topics: {
            SUMAMRY_KPI_REPORT_GENERATE_DEFAULT_DATA_CRONJOB:
                'DMS_REPORT_WRITE_GENERATE_DATA.SUMAMRY_KPI_REPORT_GENERATE_DEFAULT_DATA_CRONJOB',
            SUMMARY_REPORT_GENERATE_DEFAULT_AFTER_UPDATE_PLAN_ROUTE:
                'DMS_REPORT_WRITE_GENERATE_DATA.SUMMARY_REPORT_GENERATE_DEFAULT_AFTER_UPDATE_PLAN_ROUTE',
            SUMMARY_REPORT_BACKUP_DATA_ASYNCRONIZE:
                'DMS_REPORT_WRITE_GENERATE_DATA.SUMMARY_REPORT_BACKUP_DATA_ASYNCRONIZE',
            SUMMARY_REPORT_GENERATE_DEFAULT_DATA_ASYNCHRONIZE:
                'DMS_REPORT_WRITE_GENERATE_DATA.SUMMARY_REPORT_GENERATE_DEFAULT_DATA_ASYNCHRONIZE',
        },
        commands: {
            SUMMARY_REPORT_BACKUP_DATA: {
                cmd: 'DMS_REPORT_WRITE_GENERATE_DATA.SUMMARY_REPORT_BACKUP_DATA',
            },
            KPI_DAILY_TARGET: {
                cmd: 'DMS_REPORT_WRITE_GENERATE_DATA.KPI_DAILY_TARGET',
            },
        },
    };
//satisfies Value<'DMS_REPORT_WRITE_GENERATE_DATA'>;
